Whitespace cleanup

diff --git a/dummy-client b/dummy-client
--- a/dummy-client
+++ b/dummy-client
@@ -8,37 +8,37 @@ PROGNAME=$(basename "$0")
 # Find ancestor process given its process name and a starting PID
 # Return PID if found, 0 if not found
 find_ancestor() {
-	local name pid
-	name=$1
+    local name pid
+    name=$1
+    pid=$2
+    while [ $pid -ne 0 ]; do
+	set -- $(ps -o comm= -o ppid= -p $pid)
+	[ "$1" = "$name" ] && break
 	pid=$2
-	while [ $pid -ne 0 ]; do
-		set -- $(ps -o comm= -o ppid= -p $pid)
-		[ "$1" = "$name" ] && break
-		pid=$2
-	done
-	echo $pid
+    done
+    echo $pid
 }
 
 error() {
-	echo "$PROGNAME: Error: $1" >&2
+    echo "$PROGNAME: Error: $1" >&2
 }
 
 # Exit with error if not running under weston (perhaps we were orphaned)
 weston_pid=$(find_ancestor "weston" $$)
 if [ $weston_pid -eq 0 ]; then
-	error "not running under weston"
-	exit 1
+    error "not running under weston"
+    exit 1
 fi
 
 # Find PID of Xweston, exit with error if not found
 xweston_pid=$(find_ancestor "Xweston" $weston_pid)
 if [ $xweston_pid -eq 0 ]; then
-		error "not started by Xweston"
-		# Shutdown weston
-		kill -TERM $weston_pid
-		# If we exit before weston, we might be respawned. Give it some time
-		sleep 1
-		exit 1
+    error "not started by Xweston"
+    # Shutdown weston
+    kill -TERM $weston_pid
+    # If we exit before weston, we might be respawned. Give it some time
+    sleep 1
+    exit 1
 fi
 
 # Signal Xweston that weston is ready for connections
